spring:
  cloud:
    gateway:
      routes:
        - id: discovery-server
          uri: http://localhost:8762
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8762
          predicates:
            - Path=/eureka/**
        - id: service-one
          uri: lb://service-one
          predicates:
            - Path=/api/service-one/**
        - id: service-two
          uri: lb://service-two
          predicates:
            - Path=/api/service-two/**

server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/