spring:
  application:
    name: discovery-server

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    enabled: true
  server:
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: localhost

#logging:
#  level:
#    com.netflix.eureka: OFF
#    com.netflix.discovery: OFF
